### ISSUE TITLE
Running SeqTagger SIF on HPC 

### ISSUE THREAD

**Issue by BrendanBeahan** [novoalab/SeqTagger#1]
Hello,

I was able to succesfully run SeqTagger on our local workstation using your Docker image: However, I am encountering an issue when using a Singularity SIF built from the same container on our HPC.

To start, I build the SIF as follows:

`singularity build seqtagger.sif docker://lpryszcz/seqtagger
`

I then define the alias:

'alias seqtagger="singularity exec --nv -B $(pwd):/data seqtagger.sif"
'

And run the commmand:

`seqtagger mRNA -k /data/models/b04_RNA004 -r -i /data/test_data/RNA004 -o /data/demux
`

This resulted in the following error:

```
'[2024-11-21 13:44:11] Loading demux model... [mem:   644 MB]
/opt/app/bonito/util.py:288: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(weights, map_location=device)
[2024-11-21 13:44:12] Processing 1 dir(s)... [mem:   832 MB]
[2024-11-21 13:44:12]  /data/test_data/RNA004 with 2 file(s) [mem:   832 MB]
Traceback (most recent call last):
  File "/opt/app/mRNA", line 37, in <module>
    main()
  File "/opt/app/mRNA", line 31, in main
    demux_dirs(o.outdir, o.input, o.barcode_kit, o.batchsize, o.password, o.threads, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "demux.py", line 350, in demux.demux_dirs
  File "demux.py", line 234, in demux.demux_multi
  File "demux.py", line 246, in demux.demux_multi
  File "demux.py", line 55, in demux.demux_signals
  File "/opt/app/bonito/crf/basecall.py", line 34, in compute_scores
    scores = model(batch.to(dtype).to(device))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/bonito/crf/model.py", line 166, in forward
    return self.encoder(x)
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/bonito/nn.py", line 76, in forward
    return self.activation(self.conv(x))
                           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 370, in _conv_forward
    return F.conv1d(
           ^^^^^^^^^
RuntimeError: Input type (float) and bias type (c10::Half) should be the same'
```

Re-running the command I recieve the following:
```
[2024-11-21 14:06:34] Loading demux model... [mem:   644 MB]
/opt/app/bonito/util.py:288: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(weights, map_location=device)
[2024-11-21 14:06:34] Processing 1 dir(s)... [mem:   835 MB]
[2024-11-21 14:06:34]  file exists: /data/demux/RNA004.demux.tsv.gz [mem:   835 MB]
Traceback (most recent call last):
  File "/opt/app/mRNA", line 37, in <module>
    main()
  File "/opt/app/mRNA", line 31, in main
    demux_dirs(o.outdir, o.input, o.barcode_kit, o.batchsize, o.password, o.threads, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "demux.py", line 354, in demux.demux_dirs
  File "demux.py", line 308, in demux.plot_demux_baseQ
ValueError: could not convert string to float: '−0.2'
```

Not entirely sure how to proceed. I'm happy to run any further tests or changes to help chase down the problem if you have any recommendations. 

Best,
Brendan

**Comment by lpryszcz** [comment]
Hi Brendan, 

which GPU model do you have in HPC? 

the error suggest it doesn't support f16 (half) precision. 
```
RuntimeError: Input type (float) and bias type (c10::Half) should be the same'
```

could you please delete the output and run it again with `-v`

cheers, 
Leszek

**Comment by BrendanBeahan** [comment]
Hey Leszek,

Just realized I never followed up on this — sorry about that!

I actually ended up getting SeqTagger working not long after your reply. You were right: the issue was the GPU architecture. I had been testing on a GTX 1080 Ti, but once I switched over to an A100 node on our HPC, everything ran smoothly.

Appreciate the help!

Cheers,
Brendan
